feat: improve CI

diff --git a/.github/workflows/ci_postgresql.yml b/.github/workflows/ci_postgresql.yml
--- a/.github/workflows/ci_postgresql.yml
+++ b/.github/workflows/ci_postgresql.yml
@@ -11,14 +11,18 @@ on:
         required: false
         type: string
         default: false
+
   workflow_dispatch:
+
   push:
     branches: [ "master" ]
     paths:
       - .github/workflows/**
+      - config/**
+      - include/**
       - src/**
       - test/**
-      - database/**
+      - priv/**
       - flake.nix
       - flake.lock
       - rebar.config
@@ -28,14 +32,14 @@ on:
 env:
   PGHOST: localhost
   PGPORT: 5432
-  PGPASSWORD: postgres
-  PGUSER: postgres
+  PGPASSWORD: migraterl
+  PGUSER: migraterl
   PGDATABASE: migraterl
   CONTINUE_ON_ERROR: ${{ inputs.CONTINUE_ON_ERROR }}
 
 jobs:
   integrations:
-    name: "[v${{ inputs.PG_VERSION }}]"
+    name: "v${{ inputs.PG_VERSION }}"
     runs-on: ubuntu-latest
 
     services:
@@ -57,8 +61,23 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+
       - uses: DeterminateSystems/nix-installer-action@main
-      - name: Run Testing Suite
+
+      - name: "[Rebar] Common Tests"
         continue-on-error: ${{ fromJSON(env.CONTINUE_ON_ERROR) }}
         run: |
-          nix develop .#ci --impure -c rebar3 compile
+          nix develop .#ci --impure -c just ct
+          if [ $? -eq 0 ]; then
+            echo "status=passing" > ct_badge.txt
+          else
+            echo "status=failing" > ct_badge.txt
+            exit 1
+          fi
+
+      - name: Update Badges
+        uses: actions/upload-artifact@v4
+        with:
+          name: ci-badges
+          path: |
+            ct_badge.txt
